### ISSUE TITLE
My page doctor

### ISSUE THREAD

**Issue by Vellethe** [112axel/HealthBookingApp#10]
- [ ] allow user to toggel availibility per day in a calendar
- [ ] show upcoming apointments
- [ ] show previous apointments

**Comment by 112axel** [comment]
![Image](https://github.com/112axel/HealthBookingApp/assets/64813619/2d0f078b-bfda-49da-ba1d-8f487809ccde)

**Comment by HampusLLL** [comment]
Not done yet been a mistake with the branches.
