### ISSUE TITLE
Booking page

### ISSUE THREAD

**Issue by Vellethe** [112axel/HealthBookingApp#2]
Booking page
- [x] List of availeble times
- [x] Claim a time
- [x] filter proffesion
- [x] select specific person

Hos oss arbetar det:
Distriktssköterska 
Fysioterapeut
Kurator
Fotterapeut
Läkare - specialist i allmänmedicin
Barnmorska 
Psykolog
BVC-sköterska 
Arbetsterapeut
 
Vi tycker att det i första han är viktigt att våra patienter kan boka tid hos distriktssköterska och allmänläkare för att sedan successivt introducera fler typer av tider att boka.

**Comment by 112axel** [comment]
![Image](https://github.com/112axel/HealthBookingApp/assets/64813619/a315043c-7698-4381-b70a-cfbcc7db90d6)
